version: 0.1
phases:
    install:
        commands:
            - yarn
    build:
        commands:
            - yarn gulp build
    post_build:
        commands:
            - aws s3 sync dist s3://zichengwang.com --delete